spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root



    #����mybatis


mybatis:
  type-aliases-package: com.chixing.pojo
  mapper-locations: classpath:com/chixing/mapper/*Mapper.xml


logging:
  level: debug
  file:
    path: d://mmylog









